-- CREATE DATABASE apbd;
USE apbd;

-- CRIA TABELA TIPO
CREATE TABLE TIPO (
	CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, 
    TIPO VARCHAR(32) NOT NULL,
    PRIMARY KEY(CODIGO)
);

-- CRIA TABELA INSTRUTOR
CREATE TABLE INSTRUTOR (
	CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    INSTRUTOR VARCHAR(64) NOT NULL,
    TELEFONE VARCHAR(9) NULL,
    PRIMARY KEY(CODIGO)
);

-- CRIA TABELA CURSO
CREATE TABLE CURSO (
	CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    CURSO VARCHAR(64) NOT NULL,
    TIPO INTEGER UNSIGNED NOT NULL,
    INSTRUTOR INTEGER UNSIGNED NOT NULL, -- AS REFEERÊNCIAS A OUTRAS TABELAS SÃO ASSIM
    VALOR DOUBLE NOT NULL,
    PRIMARY KEY(CODIGO),
    INDEX FK_TIPO(TIPO),
    INDEX FK_INSTRUTOR(INSTRUTOR),
    FOREIGN KEY (TIPO) REFERENCES TIPO(CODIGO),
    FOREIGN KEY (INSTRUTOR) REFERENCES INSTRUTOR(CODIGO)
);

-- CRIA TABELA ALUNO
CREATE TABLE ALUNO (
	CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ALUNO VARCHAR(64) NOT NULL,
    ENDERECO VARCHAR(230) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    PRIMARY KEY(CODIGO)
);

-- CRIA TABELA PEDIDO
CREATE TABLE PEDIDO (
	CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ALUNO INTEGER UNSIGNED NOT NULL,
    DATAHORA DATETIME NOT NULL,
    PRIMARY KEY(CODIGO),
    INDEX FK_ALUNO(ALUNO),
    FOREIGN KEY (ALUNO) REFERENCES ALUNO(CODIGO)
);

-- CRIA PEDIDO_DETALHE
CREATE TABLE PEDIDO_DETALHE (
	PEDIDO INTEGER UNSIGNED NOT NULL,
    CURSO INTEGER UNSIGNED NOT NULL, 
    VALOR DOUBLE UNSIGNED NOT NULL,
    INDEX FK_PEDIDO(PEDIDO),
    INDEX FK_CURSO(CURSO),
    PRIMARY KEY (PEDIDO,CURSO),
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(CODIGO),
    FOREIGN KEY (CURSO) REFERENCES CURSO(CODIGO)
);

-- ALIMENTANDO AS TABELAS -------------------------------------------------------------
-- TIPO
INSERT INTO TIPO (TIPO) 
VALUES ('Banco de Dados'), ('Programação'), ('Modelagem de Dados');
SELECT * FROM TIPO; 

-- INSTRUTOR
INSERT INTO INSTRUTOR (INSTRUTOR, TELEFONE) 
VALUES ('FERNANDO', '929483950'), ('CARLOS', '969582951');
SELECT * FROM INSTRUTOR; 

-- CURSO
INSERT INTO CURSO (CURSO, TIPO, INSTRUTOR, VALOR) 
VALUES ('Java', 2, 1, 100.0), ('MYSQL', 1, 2, 90.0);
SELECT * FROM CURSO; 

-- CURSO
INSERT INTO ALUNO (ALUNO, ENDERECO, EMAIL) 
VALUES ('JUAN', 'Rua 3432', 'juan@gmail.com'), ('ANNE', 'Rua 4666', 'anne@gmail.com');
SELECT * FROM ALUNO; 

-- PEDIDO
INSERT INTO PEDIDO (ALUNO, DATAHORA) 
VALUES (1, '2022-09-02 10:13:53'), (2, '2022-09-03 11:43:37');
SELECT * FROM PEDIDO; 

-- PEDIDO_DETALHE
INSERT INTO PEDIDO_DETALHE (PEDIDO, CURSO, VALOR) 
VALUES (1, 1, 100), (2, 2, 90);
SELECT * FROM PEDIDO_DETALHE; 

