-- EXERCÍCIO 3
-- JUAN JOSÉ GOUVÊA CARDENAS
CREATE DATABASE HTC;
USE HTC;

CREATE TABLE EMPREGADOS (
 CODIGO_EMP INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NOME VARCHAR(50) NOT NULL,
 PRIMARY KEY(CODIGO_EMP)
);

CREATE TABLE PAGAMENTOS (
 CODIGO_PAG INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 EMPREGADO INT UNSIGNED NOT NULL,
 VALOR DECIMAL(10,2) NOT NULL,
 PRIMARY KEY(CODIGO_PAG),
 FOREIGN KEY (EMPREGADO) REFERENCES EMPREGADOS(CODIGO_EMP)
);

CREATE TABLE DESCONTOS (
 CODIGO_DES INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 EMPREGADO INT UNSIGNED NOT NULL,
 VALOR DECIMAL(10,2) NOT NULL,
 PRIMARY KEY(CODIGO_DES),
 FOREIGN KEY (EMPREGADO) REFERENCES EMPREGADOS(CODIGO_EMP)
);

-- INSERTAR
INSERT INTO EMPREGADOS(CODIGO_EMP, NOME) 
VALUES (0, 'LUIS'),(0, 'MARINA'),(0, 'LETICIA'),(0, 'GUSTAVO'),(0, 'MATEUS');
SELECT * FROM EMPREGADOS;

INSERT INTO PAGAMENTOS(CODIGO_PAG, EMPREGADO, VALOR) 
VALUES (0, 1, 100),(0, 2, 200),(0, 3, 300),(0, 4, 400),(0, 5, 500);
SELECT * FROM PAGAMENTOS;

INSERT INTO DESCONTOS(CODIGO_DES, EMPREGADO, VALOR) 
VALUES (0, 1, 50),(0, 2, 20),(0, 3, 30);
SELECT * FROM DESCONTOS;
