-- CREATE DATABASE EX3;
USE EX3;

CREATE TABLE EMPREGADOS (
 CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NOME VARCHAR(50) NOT NULL,
 PRIMARY KEY(CODIGO)
);

CREATE TABLE PAGAMENTOS (
 CODIGO_PAG INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 VALOR DECIMAL(10.2) NOT NULL,
 PRIMARY KEY(CODIGO_PAG)
);

CREATE TABLE DESCONTOS (
 CODIGO_DES INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 VALOR DECIMAL(10.2) NOT NULL,
 PRIMARY KEY(CODIGO_DES)
);

-- INSERTAR
INSERT INTO EMPREGADOS(NOME) 
VALUES ('LUIS'),('MARINA'),('LETICIA'),('GUSTAVO'),('MATEUS');
SELECT * FROM EMPREGADOS;

INSERT INTO PAGAMENTOS(VALOR) 
VALUES (100),(200),(300),(400),(500);
SELECT * FROM PAGAMENTOS;

INSERT INTO DESCONTOS(VALOR) 
VALUES (50),(20),(30);
SELECT * FROM DESCONTOS;
